### ISSUE TITLE
Doesn't work out of the box?

### ISSUE THREAD

**Issue by AlekzZz** [skatejs/generator-skatejs#45]
Generated new project and after running `yarn storybook` on http://localhost:6006/ i get:
`exports is not defined
ReferenceError: exports is not defined
    at Object.defineProperty.value (http://localhost:6006/static/preview.bundle.js:56010:23)
    at __webpack_require__ (http://localhost:6006/static/preview.bundle.js:679:30)
    at fn (http://localhost:6006/static/preview.bundle.js:89:20)
    at Object.<anonymous> (http://localhost:6006/static/preview.bundle.js:55453:18)
    at Object.defineProperty.value (http://localhost:6006/static/preview.bundle.js:55470:30)
    at __webpack_require__ (http://localhost:6006/static/preview.bundle.js:679:30)
    at fn (http://localhost:6006/static/preview.bundle.js:89:20)
    at webpackContext (http://localhost:6006/static/preview.bundle.js:55423:9)
    at http://localhost:6006/static/preview.bundle.js:44243:12
    at Array.forEach (<anonymous>)`

that is without touching anything.

**Comment by alexlafroscia** [comment]
Yeah, I'm pretty sure that Storybook and/or Skate has changed a whole lot since I write this generator. I'm not a Skate user myself anymore, so I'm not planning on coming back to this.

**Comment by AlekzZz** [comment]
oh i see, didn't know this project was abandoned. thanks.

**Comment by alexlafroscia** [comment]
Yeah, it's a shame but I only have so much time 🤷‍♂️

**Comment by treshugart** [comment]
@AlekzZz there's a guide for setting up skate with storybook over here http://skatejs.netlify.com/guides/storybook. Feel free to raise issues / questions in the main skatejs github project :)
